StarWarsRNNRails/config/routes.rb
Rails.application.routes.draw do
  resources :welcome,:about,:debate,:comparison,:theory

  root 'welcome#index'

  get 'debate_stage' => 'debate#show', :as => 'debate_stage'

end

StarWarsRNNRails/app/models/debate.rb
class Debate < ActiveRecord::Base
end

StarWarsRNNRails/app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

StarWarsRNNRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

StarWarsRNNRails/app/controllers/comparison_controller.rb
class ComparisonController < ApplicationController
	def index
	end
end

StarWarsRNNRails/app/controllers/debate_controller.rb
class DebateController < ApplicationController
	def show
	end

	def update
		@debate = Debate.find(1)
		@debate.update(debate_params)
	end

	private
	def debate_params
		params.require(:debate).permit(:p1,:p2,:sL)
	end
end

StarWarsRNNRails/app/controllers/theory_controller.rb
class TheoryController < ApplicationController
	def index
	end
end

StarWarsRNNRails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if @p1 && @p2 && @tL # if all parameters are available
			@debate = `python lib/assets/pythontemplate/pythontemplate.py #{@p1} #{@p2} #{@tL}` 
		end

		@debate = Debate.find(1)
		
		@p1="truman"
		@p2="roosevelt"
		@tL=1
		#@speech = exec("python pythontemplate.py {p1,p2,sL}")
		@speech = `python lib/assets/pythontemplate/pythontemplate.py #{@p1} #{@p2} #{@tL}` 
	end
end

StarWarsRNNRails/app/helpers/about_helper.rb
module AboutHelper
end

StarWarsRNNRails/app/helpers/application_helper.rb
module ApplicationHelper
end

StarWarsRNNRails/app/helpers/comparison_helper.rb
module ComparisonHelper
end

StarWarsRNNRails/app/helpers/debate_helper.rb
module DebateHelper
end

StarWarsRNNRails/app/helpers/theory_helper.rb
module TheoryHelper
end

StarWarsRNNRails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

StarWarsRNNRails/app/views/about/index.html.erb
<!-- About -> index.html.erb -->
<div class="body-wrapper container-fluid">
	<div class="info-body container">
		</br>
		<h3 style="text-align:center;">The Team</h3>
		
		<p>Vamsi Chunduru is a current Masters student in Computer Science at Johns Hopkins University. Akshay Srivatsan is a current junior undergraduate in Computer Science at Johns Hopkins University. Conan Chen is a December 2015 B.S. graduate of Biomedical Engineering at Johns Hopkins University.</p>

		<h3 style="text-align:center;">Inspiration</h3>
		<p>Our project stems from a simple question: can you model text well enough to generate original content? We’d recently seen the new Star Wars movie, and were immediately hungry for more. Unable to bear the wait until the next movie comes out, we decided to see if we could write a program to automatically generate a screenplay for a new Star Wars movie. We were also very excited by the recent release of Google’s TensorFlow API. We’re strong believers in deep learning and saw this as a perfect fit for our task.</p>


		<h3 style="text-align:center;">Challenges We Ran Into</h3>
		<p>We’ve done some work in TensorFlow previously on convolutional neural networks, which was relatively easy, but the framework for recurrent neural networks was more difficult to work with than we were expecting. It took us quite a while to understand how to generate data once we had trained the LSTM, but by reading up on the theory behind the networks we were able to figure it out. Andrej Karpathy has a blog post on RNNs that was particularly helpful in this regard.</p>

		<p>We also had some difficulty setting up the web server. It was an interesting (and painful) process of setting up the proper build environment for Ruby on Rails on our Amazon ec2 Instance and getting it to serve up our website to a public DNS.</p>

		<h3 style="text-align:center;">Accomplishments That We’re Proud Of</h3>
		<p>The model does a very good job of learning the subtleties of the way that text in a screenplay is formatted. It quickly learns that the text is broken up into paragraphs, separated by character names in all caps, often centered on the page. It also learns how to construct vaguely meaningful sentences, which is very impressive considering that it is trained on a character by character basis, and has no understanding of words beforehand.</p>


		<h3 style="text-align:center;">What We Learned</h3>
		<p>We learned a lot about how RNNs work through this project. Although we have some experience in other techniques, this was our first project on modeling text data, which came with its own unique challenges. It’s interesting to think that our model knew absolutely nothing about the structure of our data, or even the way that characters are grouped together to form words. This makes our model highly generalizable, to the point that we could apply the same network architecture to learn how to model almost any other text or even arbitrary time-series data.</p>


		<h3 style="text-align:center;">What's Next for The Force Ghost Writer</h3>
		<p>There’s still a lot of parameter tuning that can be done to improve performance. We weren’t able to conduct an exhaustive search over all hyperparameter values, but doing so could probably make our generated text a fair bit more realistic. We’re also severely limited by the size of our dataset; all in all we have only half a megabyte of data in total, which is much less than is normally needed by deep learning models. Expanding on our dataset could give us much better results.</p>



	</div>
</div>

StarWarsRNNRails/app/views/comparison/index.html.erb
<div class="body-wrapper container-fluid">
	<div class="info-body container">

		</br>
		</br>
		<h4 style="text-align:center;">An example of a script generated from our model. This one is a great example as it references topical elements of characters and setting, while presenting a script structure similar to that of the training data.</h4>
		<img src="/assets/GreatExample.jpg" class="img-thumbnail" style="width:100%;height:100%" onmouseover="bigImg(this)">
		</br>
		</br>
		</br>

		<h4 style="text-align:center;">An example of a section of the training script data.</h4>
		<img src="/assets/OriginalExample2.jpg" class="img-thumbnail" style="width:100%;height:100%" onmouseover="bigImg(this)">


	</div>

</div>

StarWarsRNNRails/app/views/debate/update.html.erb
<!-- Debate update.html.erb -->
<div class="body-wrapper container-fluid">
	<div class="info-body container">

	<h3 style="text-align:center;">Generated Script</h3>
    <% sL=@debate.sL/1000.0 %>
    <pre>
    <%= `python /home/ubuntu/PresidentialRNN/lstm.py test /home/ubuntu/PresidentialRNN/star_wars_clean.txt #{sL} #{@debate.p2} #{@debate.p1}` %>
    </pre>
    </div>

</div>

StarWarsRNNRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Force Ghost Writer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header-wrapper container-fluid">
	<div class="layer container-fluid">
		<div class="container" id="topbar">
			<h1 style="text-align:center;">The Force Ghost Writer</h1>
		</div>
	</div>
</div>

<div class="nav-wrapper" style="height:51px;">
<nav class="navbar navbar-inverse" data-spy="affix" style="height:51px;" data-offset-top="145">
  	<div class="container">
	  	<ul class="nav navbar-nav">
		    <li class=<%= 'active' if !(current_page?(about_index_path) || current_page?(theory_index_path) || current_page?(comparison_index_path)) %>><%= link_to 'HOME', welcome_index_path %></li>
		    <li class=<%= 'active' if current_page?(theory_index_path) %>><%= link_to 'THEORY', theory_index_path %></li>
		    <li class=<%= 'active' if current_page?(comparison_index_path) %>><%= link_to 'COMPARISON', comparison_index_path %></li>
		    <li class=<%= 'active' if current_page?(about_index_path) %>><%= link_to 'ABOUT', about_index_path %></li>
	  	</ul>
  	</div>
</nav>
</div>

<%= yield %>

</body>
</html>

StarWarsRNNRails/app/views/theory/index.html.erb
<div class="body-wrapper container-fluid">
	<div class="info-body container">
		</br>
		<h3 style="text-align:center;">What It Does</h3>
		<p>The specific language model we’re using is an LSTM, a specific type of recurrent neural network. The LSTM reads the scripts for Star Wars films one character at a time, and tries to predict the next character. After a few hours, it becomes very good at doing this. We can then give it a starting seed, and then have it predict the next page of text. By doing this, it is effectively generating new content inspired by the patterns it finds in the training data.</p>

		<img src="/assets/theorydiagram.jpg" class="img-thumbnail" style="width:100%;height:100%" onmouseover="bigImg(this)">
		<p style="text-align:center;">Diagram of a recurrent neural network.</p>

		<h3 style="text-align:center;">How We Built It</h3>
		<p>We used Google’s TensorFlow API to build our LSTM. TensorFlow allows us to have a strong amount of control over our network’s architecture, and it has good support for GPU computation. This meant that we were able to train efficiently on an AWS GPU instance. The network itself uses one-hot encodings for every character in the training text, and then feeds this into two stacked hidden layers per LSTM cell, and then uses a softmax classifier to predict the one-hot vector of the next character. Using the Adam optimization algorithm, we can minimize the resulting perplexity with respect to the network weights.</p>

		<p>After training, we can generate text by feeding in a short seed word, and then incrementally computing the hidden states and then the predictions for the next character. We adjust the predictions using a temperature which can control how original vs. faithful the new text is compared to the training data, and then sample the character from the adjusted distribution.</p>

		<p>For the front-end, we developed a web application in Ruby on Rails, incorporating HTML, CSS, and Bootstrap. The website provides a clean and approachable interface into the neural network parameters.</p>

	</div>

</div>

StarWarsRNNRails/app/views/welcome/index.html.erb
<!-- Welcome -> index.html.erb -->





<div class="body-wrapper container-fluid">
	<div class="info-body container">
		</br>
		<h3 style="text-align:center;">Recreate the adventure of Star Wars with new scripts at your command.</h3>
		
		</br>
		<div class="blurb-wrapper container">
			<p style="width=30px;">Below are three input fields. Seed provides a starting string for speech generation. Number of characters limits the length of the script. Finally, temperature modulates the variability of the generation model. Play around with it and see what you get! </p>
		</div>
		
		</br>
		
		<div class="center">
		<% debate = Debate.find(1) %>
		</br>

		<%= bootstrap_form_for debate do |f| %>
			<%= f.label :p1, "Seed string (10 characters max)" %></br>
			<%= f.text_field :p1, :placeholder => "e.g. Leia...", hide_label: true, :default => "" %></br>

			<%= f.label :p2, "Number of Characters (5000 to 10000)" %></br>
			<%= f.number_field :p2, hide_label: true %></br>

			<%= f.label :sL, "Temperature (range of 0 to 0.1)" %></br>
			<%= f.range_field :sL, :in => 0..100, :step => 1, hide_label: true %></br>

			<%= f.label "", "Click BB8 to start!" %></br>
			<%= f.submit "Kickoff", :type => :image, :src => "/assets/BB8_2.png", :style => "width:257px;height:373px;", :onmouseover => "bigImg(this)" %>
		<% end %> 
		</div>

		</br>
		</br>




	</div>

</div>